/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainUserInterface;

import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author nehashende
 */
public class MainJFrame extends javax.swing.JFrame {
    
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.setSize(1680, 1050);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftContainer = new javax.swing.JPanel();
        signOutBtn = new javax.swing.JButton();
        userNameInputField = new javax.swing.JTextField();
        passwordInputField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signInBtn = new javax.swing.JButton();
        mainContainer = new javax.swing.JPanel();
        homeDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(-10);

        leftContainer.setBackground(new java.awt.Color(255, 255, 255));
        leftContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signOutBtn.setText("Logout");
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });
        leftContainer.add(signOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        userNameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameInputFieldActionPerformed(evt);
            }
        });
        leftContainer.add(userNameInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, -1));
        leftContainer.add(passwordInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Password");
        leftContainer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("User Name");
        leftContainer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        signInBtn.setText("Login");
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });
        leftContainer.add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jSplitPane1.setLeftComponent(leftContainer);

        mainContainer.setLayout(new java.awt.CardLayout());

        homeDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeDisplay.setIcon(new javax.swing.ImageIcon("/Users/nehashende/Desktop/aed/AEDprojIMG/new_snow.jpeg")); // NOI18N
        homeDisplay.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        homeDisplay.setMaximumSize(new java.awt.Dimension(800, 600));
        homeDisplay.setMinimumSize(new java.awt.Dimension(800, 600));
        homeDisplay.setPreferredSize(new java.awt.Dimension(800, 600));
        mainContainer.add(homeDisplay, "card2");

        jSplitPane1.setRightComponent(mainContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        // TODO add your handling code here:
        
        signOutBtn.setEnabled(false);
        userNameInputField.setEnabled(true);
        passwordInputField.setEnabled(true);
        signInBtn.setEnabled(true);
        userNameInputField.setText("");
        passwordInputField.setText("");
        
        //mainContainer.add("logout", ua);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
    }//GEN-LAST:event_signOutBtnActionPerformed

    private void userNameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameInputFieldActionPerformed

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtnActionPerformed
        // TODO add your handling code here:
        
        try{ 
            //User ua = system.getUserAccountDirectory().authenticateUser(userNameInputField.getText(), passwordInputField.getText());
            CardLayout layout = (CardLayout) mainContainer.getLayout();
            //System.out.println("role of user ---"+ua.getRole());
            //mainContainer.add(ua.getRole().createWorkArea(mainContainer, ua, system));
            layout.next(mainContainer);
            signOutBtn.setEnabled(true);
        }
        catch(Exception e){
            System.out.println("exception ---");
            e.printStackTrace();
            System.out.println("exception due to ---"+e.getMessage());
            JOptionPane.showMessageDialog(null,"Username/Password is wrong!","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_signInBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftContainer;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPasswordField passwordInputField;
    private javax.swing.JButton signInBtn;
    private javax.swing.JButton signOutBtn;
    private javax.swing.JTextField userNameInputField;
    // End of variables declaration//GEN-END:variables
}
