/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Doctor;

import Business_Model.Ecosystem;
import BusinessModel.Patient.PatientBills;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nehashende
 */
public class DoctorVisitJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorVisitJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem ecoSystem;
    private User userAccount;
    private Patient patient;
    
    public DoctorVisitJPanel(JPanel userProcessContainer, User account, Ecosystem ecoSystem, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = account;
        this.patient = patient;
        populateBillTable();
    }
    private void populateBillTable() {
        DefaultTableModel model = (DefaultTableModel) BillTable.getModel();

        model.setRowCount(0);

        for (PatientBills b : patient.getpBills()) {

            Object[] row = new Object[7];
            row[0] = b.getName();
            row[1] = b.getOrgType();
            row[2] = b.getAmount();
            row[3] = b.getStatus();
            row[4] = b.getResult();
            
            model.addRow(row);

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillTable = new javax.swing.JTable();
        btnRequestLabTests = new javax.swing.JButton();
        btnRequestBlood = new javax.swing.JButton();
        btnRequestMedicine = new javax.swing.JButton();
        btnRequestMedicine1 = new javax.swing.JButton();
        btnRequestMedicine2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 94, 218));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1382, 60));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1730, 10));

        BillTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Department", "Amount", "Status", "Specifics"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BillTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 1420, 191));

        btnRequestLabTests.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnRequestLabTests.setForeground(new java.awt.Color(204, 0, 0));
        btnRequestLabTests.setText("Book Lab Session");
        btnRequestLabTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestLabTestsActionPerformed(evt);
            }
        });
        add(btnRequestLabTests, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 200, 60));

        btnRequestBlood.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnRequestBlood.setForeground(new java.awt.Color(204, 0, 0));
        btnRequestBlood.setText("Request Book");
        btnRequestBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestBloodActionPerformed(evt);
            }
        });
        add(btnRequestBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 170, 60));

        btnRequestMedicine.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnRequestMedicine.setForeground(new java.awt.Color(204, 0, 0));
        btnRequestMedicine.setText("Request Meal Plan");
        btnRequestMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMedicineActionPerformed(evt);
            }
        });
        add(btnRequestMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 220, 60));

        btnRequestMedicine1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnRequestMedicine1.setForeground(new java.awt.Color(204, 0, 0));
        btnRequestMedicine1.setText("Graduate");
        btnRequestMedicine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMedicine1ActionPerformed(evt);
            }
        });
        add(btnRequestMedicine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 210, 60));

        btnRequestMedicine2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnRequestMedicine2.setForeground(new java.awt.Color(204, 0, 0));
        btnRequestMedicine2.setText("Term Complete");
        btnRequestMedicine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMedicine2ActionPerformed(evt);
            }
        });
        add(btnRequestMedicine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 360, 200, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestLabTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestLabTestsActionPerformed
        // TODO add your handling code here:

        DoctorRequestLabTestJPanel doctorRequestLabTestJPanel = new DoctorRequestLabTestJPanel(userProcessContainer, userAccount, ecoSystem, patient);
        userProcessContainer.add("Request Lab Tests", doctorRequestLabTestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestLabTestsActionPerformed

    private void btnRequestBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestBloodActionPerformed
        // TODO add your handling code here:

        DoctorRequestBloodJPanel doctorRequestBloodJPanel = new DoctorRequestBloodJPanel(userProcessContainer, userAccount, ecoSystem, patient);
        userProcessContainer.add("Request Blood", doctorRequestBloodJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestBloodActionPerformed

    private void btnRequestMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMedicineActionPerformed
        // TODO add your handling code here:

        DoctorRequestMedicineJPanel doctorRequestMedicineJPanel = new DoctorRequestMedicineJPanel(userProcessContainer, userAccount, ecoSystem, patient);
        userProcessContainer.add("Request  Medicine", doctorRequestMedicineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestMedicineActionPerformed

    private void btnRequestMedicine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMedicine1ActionPerformed
        // TODO add your handling code here:
        patient.setpStatus("Ready to Discharge");
        DoctorWorkAreaJPanel doctor = new DoctorWorkAreaJPanel(userProcessContainer,userAccount,ecoSystem);
        userProcessContainer.add("Request Blood", doctor);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestMedicine1ActionPerformed

    private void btnRequestMedicine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMedicine2ActionPerformed
        // TODO add your handling code here:
        patient.setpStatus("Under Observation");
        DoctorWorkAreaJPanel doctor = new DoctorWorkAreaJPanel(userProcessContainer,userAccount,ecoSystem);
        userProcessContainer.add("Request Blood", doctor);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestMedicine2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BillTable;
    private javax.swing.JButton btnRequestBlood;
    private javax.swing.JButton btnRequestLabTests;
    private javax.swing.JButton btnRequestMedicine;
    private javax.swing.JButton btnRequestMedicine1;
    private javax.swing.JButton btnRequestMedicine2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
