/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Teacher;

import Business_Model.Ecosystem;
import BusinessModel.Student.Student;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author nehashende
 */
public class TeacherRequestBookJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherRequestBookJPanel
     */
   private JPanel userProcessContainer;
    private Ecosystem ecosystem;
    private User userAccount;
    private Student student;
    
    public TeacherRequestBookJPanel(JPanel userProcessContainer, User account, Ecosystem ecosystem, Student student) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = account;
        this.student = student;
        BloodRequestQuantityBox.addItem("Select Quantity");
        BloodRequestQuantityBox.addItem("1");
        BloodRequestQuantityBox.addItem("2");
        BloodRequestQuantityBox.addItem("3");
        BloodRequestQuantityBox.addItem("4");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblRequestBloodQuantity = new javax.swing.JLabel();
        BloodRequestQuantityBox = new javax.swing.JComboBox<>();
        Request1 = new javax.swing.JButton();
        btnProcessRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Request Book");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 40, 1274, -1));

        lblRequestBloodQuantity.setBackground(new java.awt.Color(255, 255, 255));
        lblRequestBloodQuantity.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblRequestBloodQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblRequestBloodQuantity.setText("Select Quantity");
        add(lblRequestBloodQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 260, 40));

        BloodRequestQuantityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodRequestQuantityBoxActionPerformed(evt);
            }
        });
        add(BloodRequestQuantityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 180, 40));

        Request1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Request1.setText(" Back");
        Request1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Request1ActionPerformed(evt);
            }
        });
        add(Request1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 140, 40));

        btnProcessRequest.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnProcessRequest.setText("Process Request");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });
        add(btnProcessRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 197, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BloodRequestQuantityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodRequestQuantityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodRequestQuantityBoxActionPerformed

    private void Request1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Request1ActionPerformed
        // TODO add your handling code here:
        TeacherVisitJPanel doctorVisit = new TeacherVisitJPanel(userProcessContainer, userAccount, ecosystem, student);
        userProcessContainer.add("Visit Doctor", doctorVisit);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_Request1ActionPerformed

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed
        // TODO add your handling code here:

        if (!((String) BloodRequestQuantityBox.getSelectedItem()).equals("Select Quantity")) {

            student.setsBookStoreStatus("Requested");
            student.setsBooksQuantity((String) BloodRequestQuantityBox.getSelectedItem());

            JOptionPane.showMessageDialog(null, "Blood Request Sent", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            TeacherVisitJPanel doctorVisit = new TeacherVisitJPanel(userProcessContainer, userAccount, ecosystem, student);
            userProcessContainer.add("Attend lecture", doctorVisit);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnProcessRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BloodRequestQuantityBox;
    private javax.swing.JButton Request1;
    private javax.swing.JButton btnProcessRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRequestBloodQuantity;
    // End of variables declaration//GEN-END:variables
}
