/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Police;

import Business_Model.Ecosystem;
import BusinessModel.Student.Student;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nehashende
 */

public class PoliceWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PoliceWorkAreaJPanel
     */
    JPanel userProcessContainer;
    User account;
    Ecosystem ecoSystem;
    
    public PoliceWorkAreaJPanel(JPanel userProcessContainer, User account, Ecosystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = business;
        this.account = account;
        populateStudentTable();
        populateStudentTable1();
    }

    private void populateStudentTable() {
        DefaultTableModel model = (DefaultTableModel) managePatientTable.getModel();

        model.setRowCount(0);

        for (Student stud : ecoSystem.getPoliceRecords().getPoliceRecordsList()) {

            Object[] row = new Object[8];
            row[0] = stud.getsFirstName();
            row[1] = stud.getsLastName();           
            row[2] = stud.getsFellowshipID();
            row[3] = stud.getsAge();
            row[4] = stud.getsAddress();
            row[5] = stud.getsEmailAddress();
            row[6] = stud.getsPoliceStatus();
            row[7] = stud;
            if(stud.getsPoliceStatus().equals("Verifying")){
            model.addRow(row);}

        }
    }
    
    private void populateStudentTable1() {
        DefaultTableModel model = (DefaultTableModel) managePatientTable1.getModel();

        model.setRowCount(0);

        for (Student s : ecoSystem.getPoliceRecords().getPoliceRecordsList()) {

            Object[] row = new Object[8];
            row[0] = s.getsFirstName();
            row[1] = s.getsLastName();
            row[2] = s.getsFellowshipID();
            row[3] = s.getsAge();
            row[4] = s.getsAddress();
            row[5] = s.getsEmailAddress();
            row[6] = s.getsPoliceStatus();
            row[7] = s;
            if(!s.getsPoliceStatus().equals("Verifying")){
            model.addRow(row);}

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        managePatientTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        managePatientTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POLICE DEPATMENT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1260, 80));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, 1260, 30));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 130, 120));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setText("VERIFICATION REQUEST");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 334, 21));

        managePatientTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        managePatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last", "Id", "Age", "Address", "Email", "Police Verification"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(managePatientTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1290, 140));

        jButton1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButton1.setText("View Details of Verification");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 316, 37));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setText("PAST RECORDS");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 313, 21));

        managePatientTable1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        managePatientTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last", "Id", "Age", "Address", "Email", "Police Verification"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(managePatientTable1);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 1260, 191));

        jButton2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButton2.setText("View Details of Past Records");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 770, 310, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = managePatientTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{

            Student d = (Student) managePatientTable.getValueAt(selectedRow, 7);
            PersonInfo bill = new PersonInfo(userProcessContainer,ecoSystem, d,account);
            userProcessContainer.add("Police Person Info", bill);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = managePatientTable1.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{

            Student d = (Student) managePatientTable1.getValueAt(selectedRow, 7);
            //d.get
            PastInfo bill = new PastInfo(userProcessContainer,ecoSystem, d,account);
            userProcessContainer.add("Past Information", bill);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable managePatientTable;
    private javax.swing.JTable managePatientTable1;
    // End of variables declaration//GEN-END:variables
}
