/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Transport;
import BusinessModel.Transport.Transport;
import BusinessModel.UserAccount.User;
import Business_Model.Ecosystem;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

/**
 *
 * @author aniketbhore
 */
public class CurrentStudentDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CurrentStudentDetailsJPanel
     */
    private final JPanel userProcessContainer;
    private final Ecosystem ecoSystem;
    private User userAccount;
    private Transport bus;

    public CurrentStudentDetailsJPanel(JPanel userProcessContainer, User account, Ecosystem system, Transport bus) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecoSystem = system;
        this.bus = bus;

        lblFirstName.setText(bus.getBusStudentsList().get(bus.getBusStudentsList().size() - 1).getsFirstName());
        lblLastName.setText(bus.getBusStudentsList().get(bus.getBusStudentsList().size() - 1).getsLastName());
        lblLocation.setText(bus.getBusStudentsList().get(bus.getBusStudentsList().size() - 1).getsPickupLocation());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPatientFirstName = new javax.swing.JLabel();
        lblPatientLastName = new javax.swing.JLabel();
        lblPatientLocation = new javax.swing.JLabel();
        lblLocation = new javax.swing.JTextField();
        lblLastName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JTextField();
        btnSetFree1 = new javax.swing.JButton();
        btnSetFree = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(153, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 10, 1409, 80));

        lblPatientFirstName.setBackground(new java.awt.Color(0, 153, 204));
        lblPatientFirstName.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblPatientFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientFirstName.setText("First Name");
        add(lblPatientFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        lblPatientLastName.setBackground(new java.awt.Color(15, 85, 177));
        lblPatientLastName.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblPatientLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientLastName.setText("Last Name");
        add(lblPatientLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        lblPatientLocation.setBackground(new java.awt.Color(15, 85, 177));
        lblPatientLocation.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblPatientLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientLocation.setText("Location");
        add(lblPatientLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));
        add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 210, 30));
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 210, 30));

        lblFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFirstNameActionPerformed(evt);
            }
        });
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 210, 30));

        btnSetFree1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnSetFree1.setText("Back");
        btnSetFree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetFree1ActionPerformed(evt);
            }
        });
        add(btnSetFree1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 130, 38));

        btnSetFree.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnSetFree.setText("Set Free");
        btnSetFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetFreeActionPerformed(evt);
            }
        });
        add(btnSetFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 170, 38));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, 1432, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetFree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetFree1ActionPerformed
        // TODO add your handling code here:
        DisplayTransportStudentJPanel displayAmbulancePatientJPanel = new DisplayTransportStudentJPanel(userProcessContainer, userAccount, ecoSystem);
        userProcessContainer.add("Bus Display", displayAmbulancePatientJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSetFree1ActionPerformed

    private void btnSetFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetFreeActionPerformed
        // TODO add your handling code here:

        bus.setStatus("Free");
        JOptionPane.showMessageDialog(null, "Status Changed To Free");
        DisplayTransportStudentJPanel displayAmbulancePatientJPanel = new DisplayTransportStudentJPanel(userProcessContainer, userAccount, ecoSystem);
        userProcessContainer.add("Bus Display", displayAmbulancePatientJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSetFreeActionPerformed

    private void lblFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFirstNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetFree;
    private javax.swing.JButton btnSetFree1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lblFirstName;
    private javax.swing.JTextField lblLastName;
    private javax.swing.JTextField lblLocation;
    private javax.swing.JLabel lblPatientFirstName;
    private javax.swing.JLabel lblPatientLastName;
    private javax.swing.JLabel lblPatientLocation;
    // End of variables declaration//GEN-END:variables
}
