/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Transport;
import BusinessModel.Transport.Transport;
import Business_Model.Ecosystem;
import BusinessModel.Student.Student;
import BusinessModel.Roles.Student_role;
import BusinessModel.UserAccount.User;
//import BusinessUtil.GoogleMaps.GoogleMapsAmbulanceJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import MainUserInterface.ReceptionRole.ReceptionWorkAreaJPanel;
/**
 *
 * @author aniketbhore
 */
public class ReceptionTransportWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionTransportWorkAreaJPanel
     */
   private final JPanel userProcessContainer;
    private final Ecosystem ecoSystem;
    User userAccount;
    Transport bus;

    public ReceptionTransportWorkAreaJPanel(JPanel userProcessContainer, Ecosystem ecoSystem, User userAccount, Transport bus) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.bus = bus;
    }
    
    public ReceptionTransportWorkAreaJPanel(JPanel userProcessContainer, Ecosystem ecoSystem, User userAccount, Transport bus, Student studentDetails) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.bus = bus;
        setUpTextFields(studentDetails);
    }
    
    public void setUpTextFields(Student s){
        txtPatientUserName.setText(s.getsUserName());
        txtPatientFirstName.setText(s.getsFirstName());
        txtPatientLastName.setText(s.getsLastName());
        txtPatientLocation.setText(s.getsPickupLocation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPatientFirstName = new javax.swing.JLabel();
        lblPatientLastName = new javax.swing.JLabel();
        lblPatientLocation = new javax.swing.JLabel();
        lblPatientPassword = new javax.swing.JLabel();
        lblPatientUserName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtPatientPassword = new javax.swing.JTextField();
        txtPatientUserName = new javax.swing.JTextField();
        txtPatientLocation = new javax.swing.JTextField();
        txtPatientLastName = new javax.swing.JTextField();
        txtPatientFirstName = new javax.swing.JTextField();
        Route_JButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register For Trasport Service");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 1432, 80));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1432, 10));

        lblPatientFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientFirstName.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblPatientFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientFirstName.setText("First Name");
        add(lblPatientFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        lblPatientLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientLastName.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblPatientLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientLastName.setText("Last Name");
        add(lblPatientLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        lblPatientLocation.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientLocation.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblPatientLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientLocation.setText("Location");
        add(lblPatientLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 174, -1));

        lblPatientPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientPassword.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblPatientPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientPassword.setText("Password");
        add(lblPatientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, -1, -1));

        lblPatientUserName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientUserName.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblPatientUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientUserName.setText("User Name");
        add(lblPatientUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, 20));

        btnSubmit.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 154, 40));
        add(txtPatientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 250, 30));
        add(txtPatientUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 250, 30));

        txtPatientLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientLocationActionPerformed(evt);
            }
        });
        add(txtPatientLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 250, 30));
        add(txtPatientLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 250, 30));
        add(txtPatientFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 250, 30));

        Route_JButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Route_JButton.setForeground(new java.awt.Color(255, 255, 255));
        Route_JButton.setText("VIEW ROUTE");
        Route_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Route_JButtonActionPerformed(evt);
            }
        });
        add(Route_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 750, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (ecoSystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtPatientUserName.getText())) {

            Student student = new Student(txtPatientUserName.getText());
            student.setsFirstName(txtPatientFirstName.getText());
            student.setsLastName(txtPatientLastName.getText());
            student.setsPickupLocation(txtPatientLocation.getText());
            student.setsStatus("NewStudent");
            student.setsBookStoreStatus("NewStudent");
            student.setsInventoryStatus("NewStudent");
            student.setsLabStatus("NewStudent");
            student.setsDateOfAdmit(java.util.Calendar.getInstance().getTime());
            bus.setStatus("Busy");
            bus.setPickupLocation(txtPatientLocation.getText());
            bus.getBusStudentsList().add(student);

            ecoSystem.getUserAccountDirectory().createUser(txtPatientUserName.getText(), txtPatientPassword.getText(), null, new Student_role());
            ecoSystem.getStudentDirectory().createStudent(student);
                    //getPatientDirectory().createPatient(student);
            for (Student s : ecoSystem.getStudentDirectory().getStudentList()) {
                if (s.getsUserName().equals(txtPatientUserName.getText())) {
                    ecoSystem.getStudentDirectory().AddBill(s, "Seat Charge", "School", "Ammount");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username is not Unique.");
        }

        JOptionPane.showMessageDialog(null, "You are enrolled for transport services");

        ReceptionWorkAreaJPanel receptionWorkAreaJPanel = new ReceptionWorkAreaJPanel(userProcessContainer, userAccount, ecoSystem);
        userProcessContainer.add("Reception Work Area", receptionWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtPatientLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientLocationActionPerformed

    private void Route_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Route_JButtonActionPerformed
        // TODO add your handling code here:
        /*ReceptionWorkAreaJPanel receptionWorkAreaJPanel = new ReceptionWorkAreaJPanel(userProcessContainer, userAccount, ecoSystem);
        userProcessContainer.add("Reception Work Area", receptionWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        */
        Student stud = new Student(txtPatientUserName.getText());
        stud.setsFirstName(txtPatientFirstName.getText());
        stud.setsLastName(txtPatientLastName.getText());
        stud.setsPickupLocation(txtPatientLocation.getText());
        stud.setsStatus("NewStudent");
        stud.setsBookStoreStatus("NewStudent");
        stud.setsInventoryStatus("NewStudent");
        stud.setsLabStatus("NewPatient");
        // stud.setsDateOfAdmit(java.util.Calendar.getInstance().getTime());

        //       GoogleMapsAmbulanceJPanel GoogleMapsWorkAreaJPanel = new GoogleMapsAmbulanceJPanel(userProcessContainer, ecoSystem, userAccount, ambulance, txtPatientLocation.getText(), patient);
        //        userProcessContainer.add("Google Maps Work Area", GoogleMapsWorkAreaJPanel);
        //        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //        layout.next(userProcessContainer);
    }//GEN-LAST:event_Route_JButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Route_JButton;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPatientFirstName;
    private javax.swing.JLabel lblPatientLastName;
    private javax.swing.JLabel lblPatientLocation;
    private javax.swing.JLabel lblPatientPassword;
    private javax.swing.JLabel lblPatientUserName;
    private javax.swing.JTextField txtPatientFirstName;
    private javax.swing.JTextField txtPatientLastName;
    private javax.swing.JTextField txtPatientLocation;
    private javax.swing.JTextField txtPatientPassword;
    private javax.swing.JTextField txtPatientUserName;
    // End of variables declaration//GEN-END:variables
}
